name: CI
on:
  push:
    branches: [ main ]
    tags: ['*']

  pull_request:

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Course Management Tools Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt-hotspot
          cache: 'sbt'

      - name: Setup Coursier
        run: |
          curl -fLo coursier https://git.io/coursier-cli &&
          chmod +x coursier &&
          ./coursier

      - name: Check code formatting
        run: sbt "scalafmtCheckAll ; scalafmtSbtCheck"

      - name: Run tests
        run: sbt test

  run-tests-windows:
    runs-on: windows-latest

    steps:

      - name: Checkout Course Management Tools Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt-hotspot
          cache: 'sbt'

      - name: Run tests
        shell: bash
        run: sbt test
