name: CI
on:
  push:
    branches: [ main ]

  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout Course Management Tools Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt-hotspot
          cache: 'sbt'

      - name: Check code formatting
        run: sbt "scalafmtCheckAll ; scalafmtSbtCheck"

      - name: Run tests
        shell: bash
        run: sbt test
